return {
	-- {
	-- 	"mattn/emmet-vim",
	-- 	ft = { "svelte", "html", "vue", "php" },
	-- 	config = function() end,
	-- },
	-- {
	-- 	-- `lazydev` configures Lua LSP for your Neovim config, runtime and plugins
	-- 	-- used for completion, annotations and signatures of Neovim apis
	-- 	"folke/lazydev.nvim",
	-- 	ft = "lua",
	-- 	opts = {
	-- 		library = {
	-- 			-- Load luvit types when the `vim.uv` word is found
	-- 			{ path = "luvit-meta/library", words = { "vim%.uv" } },
	-- 		},
	-- 	},
	-- },
	-- { "Bilal2453/luvit-meta", lazy = true },
	-- {
	-- 	-- Main LSP Configuration
	-- 	"neovim/nvim-lspconfig",
	-- 	dependencies = {
	-- 		-- Automatically install LSPs and related tools to stdpath for Neovim
	-- 		{ "williamboman/mason.nvim", config = true }, -- NOTE: Must be loaded before dependants
	-- 		"williamboman/mason-lspconfig.nvim",
	-- 		"WhoIsSethDaniel/mason-tool-installer.nvim",
	--
	-- 		-- Useful status updates for LSP.
	-- 		-- NOTE: `opts = {}` is the same as calling `require('fidget').setup({})`
	-- 		{ "j-hui/fidget.nvim", opts = {} },
	-- 	},
	-- 	config = function()
	-- 		vim.api.nvim_create_autocmd("LspAttach", {
	-- 			group = vim.api.nvim_create_augroup("kickstart-lsp-attach", { clear = true }),
	-- 			callback = function(event)
	-- 				local map = function(keys, func, desc, mode)
	-- 					mode = mode or "n"
	-- 					vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = "LSP: " .. desc })
	-- 				end
	-- 				map("gd", require("telescope.builtin").lsp_definitions, "[G]oto [D]efinition")
	-- 				map("gr", require("telescope.builtin").lsp_references, "[G]oto [R]eferences")
	-- 				map("gI", require("telescope.builtin").lsp_implementations, "[G]oto [I]mplementation")
	-- 				map("<leader>D", require("telescope.builtin").lsp_type_definitions, "Type [D]efinition")
	-- 				map("<leader>ds", require("telescope.builtin").lsp_document_symbols, "[D]ocument [S]ymbols")
	-- 				map(
	-- 					"<leader>ws",
	-- 					require("telescope.builtin").lsp_dynamic_workspace_symbols,
	-- 					"[W]orkspace [S]ymbols"
	-- 				)
	-- 				map("<leader>lr", vim.lsp.buf.rename, "[L]sp [R]ename")
	-- 				map("<leader>la", vim.lsp.buf.code_action, "[L]sp Code [A]ction", { "n", "x" })
	-- 				map("gD", vim.lsp.buf.declaration, "[G]oto [D]eclaration")
	-- 				local client = vim.lsp.get_client_by_id(event.data.client_id)
	-- 				if client and client.supports_method(vim.lsp.protocol.Methods.textDocument_documentHighlight) then
	-- 					local highlight_augroup =
	-- 						vim.api.nvim_create_augroup("kickstart-lsp-highlight", { clear = false })
	-- 					vim.api.nvim_create_autocmd({ "CursorHold", "CursorHoldI" }, {
	-- 						buffer = event.buf,
	-- 						group = highlight_augroup,
	-- 						callback = vim.lsp.buf.document_highlight,
	-- 					})
	--
	-- 					vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
	-- 						buffer = event.buf,
	-- 						group = highlight_augroup,
	-- 						callback = vim.lsp.buf.clear_references,
	-- 					})
	--
	-- 					vim.api.nvim_create_autocmd("LspDetach", {
	-- 						group = vim.api.nvim_create_augroup("kickstart-lsp-detach", { clear = true }),
	-- 						callback = function(event2)
	-- 							vim.lsp.buf.clear_references()
	-- 							vim.api.nvim_clear_autocmds({ group = "kickstart-lsp-highlight", buffer = event2.buf })
	-- 						end,
	-- 					})
	-- 				end
	-- 				vim.lsp.inlay_hint.enable(true)
	-- 				if client and client.supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint) then
	-- 					map("<leader>th", function()
	-- 						vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled({ bufnr = event.buf }))
	-- 					end, "[T]oggle Inlay [H]ints")
	-- 				end
	-- 				if client and client.name == "svelte" then
	-- 					vim.api.nvim_create_autocmd("BufWritePost", {
	-- 						pattern = { "*.js", "*.ts" },
	-- 						group = vim.api.nvim_create_augroup("svelte_ondidchangetsorjsfile", { clear = true }),
	-- 						callback = function(ctx)
	-- 							-- Here use ctx.match instead of ctx.file
	-- 							client.notify("$/onDidChangeTsOrJsFile", { uri = ctx.match })
	-- 						end,
	-- 					})
	-- 				end
	-- 			end,
	-- 		})
	--
	-- 		if vim.g.have_nerd_font then
	-- 			local signs = { ERROR = "", WARN = "", INFO = "", HINT = "" }
	-- 			local diagnostic_signs = {}
	-- 			for type, icon in pairs(signs) do
	-- 				diagnostic_signs[vim.diagnostic.severity[type]] = icon
	-- 			end
	-- 			vim.diagnostic.config({ signs = { text = diagnostic_signs } })
	-- 		end
	--
	-- 		require("mason").setup()
	-- 		local mason_registry = require("mason-registry")
	--
	-- 		local capabilities = vim.lsp.protocol.make_client_capabilities()
	-- 		capabilities = vim.tbl_deep_extend("force", capabilities, require("blink.cmp").get_lsp_capabilities())
	--
	-- 		-- Enable the following language servers
	-- 		--  Feel free to add/remove any LSPs that you want here. They will automatically be installed.
	-- 		--
	-- 		--  Add any additional override configuration in the following tables. Available keys are:
	-- 		--  - cmd (table): Override the default command used to start the server
	-- 		--  - filetypes (table): Override the default list of associated filetypes for the server
	-- 		--  - capabilities (table): Override fields in capabilities. Can be used to disable certain LSP features.
	-- 		--  - settings (table): Override the default settings passed when initializing the server.
	-- 		--        For example, to see the options for `lua_ls`, you could go to: https://luals.github.io/wiki/settings/
	-- 		local servers = {
	-- 			-- clangd = {},
	-- 			-- gopls = {
	-- 			-- 	settings = {
	-- 			-- 		gopls = {
	-- 			-- 			["ui.inlayhint.hints"] = {
	-- 			-- 				assignVariableTypes = true,
	-- 			-- 				compositeLiteralFields = true,
	-- 			-- 				compositeLiteralTypes = true,
	-- 			-- 				constantValues = true,
	-- 			-- 				functionTypeParameters = true,
	-- 			-- 				parameterNames = true,
	-- 			-- 				rangeVariableTypes = true,
	-- 			-- 			},
	-- 			-- 		},
	-- 			-- 	},
	-- 			-- },
	-- 			-- Vue 3
	-- 			volar = {},
	-- 			-- TypeScript
	-- 			ts_ls = {
	-- 				filetypes = { "typescript", "javascript", "javascriptreact", "typescriptreact", "vue" },
	-- 				init_options = {
	-- 					plugins = {
	-- 						{
	-- 							name = "@vue/typescript-plugin",
	-- 							location = vim.fn.stdpath("data")
	-- 								.. "/mason/packages/vue-language-server/node_modules/@vue/language-server",
	-- 							languages = { "vue" },
	-- 						},
	-- 					},
	-- 				},
	-- 			},
	--
	-- 			lua_ls = {
	-- 				-- cmd = { ... },
	-- 				-- filetypes = { ... },
	-- 				-- capabilities = {},
	-- 				settings = {
	-- 					Lua = {
	-- 						completion = {
	-- 							callSnippet = "Replace",
	-- 						},
	-- 						-- You can toggle below to ignore Lua_LS's noisy `missing-fields` warnings
	-- 						-- diagnostics = { disable = { 'missing-fields' } },
	-- 					},
	-- 				},
	-- 			},
	-- 			intelephense = {
	-- 				root_dir = function()
	-- 					return vim.loop.cwd()
	-- 				end,
	-- 				settings = {},
	-- 			},
	-- 		}
	--
	-- 		-- Ensure the servers and tools above are installed
	-- 		--  To check the current status of installed tools and/or manually install
	-- 		--  other tools, you can run
	-- 		--    :Mason
	-- 		--
	-- 		--  You can press `g?` for help in this menu.
	-- 		require("mason").setup()
	--
	-- 		-- You can add other tools here that you want Mason to install
	-- 		-- for you, so that they are available from within Neovim.
	-- 		local ensure_installed = vim.tbl_keys(servers or {})
	-- 		vim.list_extend(ensure_installed, {
	-- 			"stylua", -- Used to format Lua code
	-- 		})
	-- 		require("mason-tool-installer").setup({ ensure_installed = ensure_installed })
	--
	-- 		require("mason-lspconfig").setup({
	-- 			handlers = {
	-- 				function(server_name)
	-- 					local server = servers[server_name] or {}
	-- 					-- This handles overriding only values explicitly passed
	-- 					-- by the server configuration above. Useful when disabling
	-- 					-- certain features of an LSP (for example, turning off formatting for ts_ls)
	-- 					server.capabilities = vim.tbl_deep_extend("force", {}, capabilities, server.capabilities or {})
	-- 					require("lspconfig")[server_name].setup(server)
	-- 				end,
	-- 			},
	-- 		})
	-- 	end,
	-- },
}
